import './globals.css'
import '../../configureAmplify'
import { Open_Sans } from 'next/font/google'
import NavBar from './components/nabar'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <NavBar />
        {children}
        </body>
    </html>
  )
}
